server:
  port: 9001
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO}
          username: ${USERNAME}
          password: ${PASSWORD}
#          default-label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://16.171.129.12:9000/eureka/
      defaultZone: http://localhost:9000/eureka/
  instance:
    preferIpAddress: true